lr_decay_epoch: 100
exp_lr: False
tblog_interval: 100
pretrained: False
nodropout: False
lr_decay_rate: 0.1
nesterov: False
g_estim: none
epoch_iters: 0
gvar_log_iter: 100
gvar_estim_iter: 10
gvar_start: 0
g_optim: False
g_optim_start: 1
g_epoch: False
g_resume: False
g_batch_size: -1
niters: 0
